### PR TITLE
returned value

### PR DESCRIPTION
**Pull request by doowb**
This PR changes what may be returned to be more in line with `defaultTo`.

Previously, `null` was returned if none of the values were valid.
Now, if none of the values are valid, the last argument passed in will be returned. This is more in line with `defaultTo` but will work with multiple arguments.

This PR also add a `.strict` method that acts just like the normal `koalas` function, but only checks `undefined` and `NaN`.

@phated please take a look and let me know if this is still in line with what you were looking for.

@jonschlinkert the `.strict` method should accomplish what we talked about.

### CODE REVIEW

**Comment by phated** [comment]
@doowb I think I'm fine with either behavior because a default of `null` at the end seems weird.

**Comment by jonschlinkert** [comment]
@phated agreed. fwiw I suggested `.strict`, but I was saying we could use that if you expected `null` to be returned for some reason. 

@doowb / @phated how about if we just change the currently published version so that it doesn't return null?

**Comment by phated** [comment]
> @doowb / @phated how about if we just change the currently published version so that it doesn't return null?

I'm not sure I understand this suggestion?

**Comment by jonschlinkert** [comment]
> I'm not sure I understand this suggestion?

Sorry, I'm agreeing with what you said in the following quote:

> I'm fine with either behavior because a default of null at the end seems weird.

So, I'm suggesting that instead of merging @doowb's changes, we simply not return a default of null.

**Comment by phated** [comment]
@doowb any more movement on this?

**Comment by doowb** [comment]
Sorry, lost track of this one.

> instead of merging @doowb's changes, we simply not return a default of null.

So we can just not return anything (which will return `undefined`), which is similar to what [defined](https://github.com/substack/defined) does. Or we can return the last argument which will produce the same results as lodash's `defaultTo` method when only 2 arguments are passed in.

I prefer the second option. I'll update this PR to that unless there's any objections.

**Comment by jonschlinkert** [comment]
to be clear, @doowb is saying that `null` would not be returned if it was the first argument. I think it should be.

**Comment by doowb** [comment]
I just looked at how `koalas` is being used in `vinyl-fs` and it's expecting that if the first argument is `null`, then the second argument will be returned.

I'll merge this, and we can look at adding a method to cover the use case when `null` is expected to be a valid value. That method would just check if the first value is `undefined`, then return the second value. I can see how both approaches are useful in different situations.

**Pull request merged**
